### ISSUE TITLE
importing starter code takes forever

### ISSUE THREAD

**Issue by Tanveerdhiman** [education/classroom#1623]
**Describe the bug**
importing starter code takes forever when accepting a assignment

**Screenshots**
![image](https://user-images.githubusercontent.com/17951930/46353850-ca786e00-c67a-11e8-8932-d46068ebd2c0.png)

**Additional context**
assignment link
https://classroom.github.com/assignment-invitations/217b811477799fc3887ab5b688249442

**Comment by PohaoGit** [comment]
@Tanveerdhiman I encounter this issue too, have you found a solution?

**Comment by BenEmdon** [comment]
Thanks for writing in 👋
We have escalated this issue to the source imports team.
This problem occurs when there is a high demand on the source import infrastructure, unfortunately it happens sporadically.

The source import team is working on scaling their infrastructure. In the meantime, I would suggest trying the assignment creation process again (by going back to your invitation link).

If that doesn't work for you, please report back in on this issue.

**Comment by johndbritton** [comment]
@Tanveerdhiman @PohaoGit This issue should be resolved for both of you. Please try again and reopen this if the issue persists.

**Comment by mangeshhambarde** [comment]
@johndbritton I still see this issue at https://classroom.github.com/assignment-invitations/89eea7c971b83b90c476d75915991476/setup.

**Comment by johndbritton** [comment]
@BenEmdon Can you please investigate the specific case for @mangeshhambarde? I think I addressed this issue for the majority of users, but this particular account may not have had a valid auth token at the time that I ran the webhook backfill.

**Comment by BenEmdon** [comment]
I can confirm that the webhook exists for the org that @mangeshhambarde 
I'll investigate @mangeshhambarde's assignment in particular 👀

**Comment by BenEmdon** [comment]
@mangeshhambarde I have gone ahead and unstuck your assignment repo for you (go to 
https://classroom.github.com/assignment-invitations/89eea7c971b83b90c476d75915991476)

It looks like the reason it was stuck "importing" is because GitHub.com experienced and outage at the time that you tried to create your assignment repo (on Monday 22 Oct 2018).

We are currently doing work in #1631 to prevent students from being stuck from GitHub.com outages.

**Comment by metrolearn** [comment]
+1  the process has been hanging for close to 40 minutes now. for me.  Refresh does not resolve the issue.

**Comment by BenEmdon** [comment]
Hey @metrolearn, if you are experiencing this issue please open a new issue (so we can keep track of it). This issue was due to a GitHub.com service outrage, and the cause of your issue might be different.
Thanks for your patience.

**Comment by belgort-clark** [comment]
I'm currently having this same issue today with an assignment. Is there a GitHub outage?

**Comment by bbtong** [comment]
Same issue for Cal students.

**Comment by fywu85** [comment]
Can someone look into this? I have been stuck with the following for a day...
![image](https://user-images.githubusercontent.com/8881002/53297981-6bf38e00-37db-11e9-9dd7-a2f6bc07c28d.png)

**Comment by hroncok** [comment]
It is happening again for us:

![_](https://user-images.githubusercontent.com/2401856/53298487-2660b080-382f-11e9-8f1f-0408f1126524.png)

**Comment by ronz243** [comment]
Happening since 1 day

![screenshot 2019-02-24 at 10 27 40 am](https://user-images.githubusercontent.com/5845142/53303418-ea255400-381e-11e9-9fde-cfbda26513d7.png)

**Comment by Hugo0** [comment]
Can this issue be reopened? Happening to me as well:

![image](https://user-images.githubusercontent.com/12943235/53307100-314e2c00-3895-11e9-8ac7-8c938c357b8a.png)

**Comment by BenEmdon** [comment]
Duplicate of #1778
Please look there for updates and information ☝️

**Comment by BenEmdon** [comment]
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Comment by maciejjankowski** [comment]
Stuck with our org

<img width="1038" alt="obraz" src="https://user-images.githubusercontent.com/2905995/54033099-b13c9600-41b3-11e9-8ff1-c5123800609e.png">
