### ISSUE TITLE
Can't Create Classroom

### ISSUE THREAD

**Issue by Mr-9riffin** [education/classroom#2278]
**Describe the bug**
After clicking create classroom, when I click on the organization that I created a message in red says "You are not permitted to add this organization as a classroom"

I recently changed my GitHub user name and I noticed that the GitHub Classroom user name is still my old username.  Also, when I click on my user icon (top right corner) and then click on my user name I get a 404 page.

**Expected behavior**
I would expect to be able to create a new classroom linked to the organization like i see in the instructional video.

**Screenshots**
Error
![image](https://user-images.githubusercontent.com/33555730/63482436-880c7b00-c45e-11e9-9e93-92974e9983ad.png)

**Additional context**

**Comment by d12** [comment]
Hey @Mr-9riffin 

You should be good to go. We have a bug when users change their handle which should be resolved soon, but for now I've fixed your account manually. Thanks for the report!

**Comment by jason-lim** [comment]
Hi,

I'm not too sure if I should open a new issue. But I'm facing the same issue described above.
I've changed my username and now I couldn't create classrooms. Also, the username reflected at the classroom page is still showing the old username. Thanks!

**Comment by Mr-9riffin** [comment]
It's working!  Thanks!

**Comment by d12** [comment]
@jason-lim , you're also fixed now :)

**Comment by tien-nguyen-duc** [comment]
I have got the same problem. The old name is still displayed in my education account, and I cannot create classrooms.
Thanks

**Comment by radiobed** [comment]
I have the same issue (changed username). Could you please help me out?

Many thanks!

**Comment by d12** [comment]
Sorry about that @radiobed , you're all fixed!
